---
- include_tasks: setup-Amazon.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'


- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

